### ISSUE TITLE
Test case failing

### ISSUE THREAD

**Issue by kenken64** [kulapio/libra-core#22]
console.log test/client.test.ts:35
      Account 1 address 4ab38e4fc265511766b075f3d03aa1acf91b9fe3bc48c77381d4b1beed2204e3

  ● LibraClient › should get accountState correctly

    13 INTERNAL: Failed to parse server response

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1204:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:845:24)

  ● LibraClient › should query account state and transfer

    13 INTERNAL: Failed to parse server response

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1204:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:845:24)

  ● LibraClient › should rotatekey and transfer correctly

    13 INTERNAL: Failed to parse server response

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1204:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:845:24)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       3 failed, 14 passed, 17 total
Snapshots:   0 total
Time:        10.799s

**Comment by kenken64** [comment]
How do you regenerate the proto stubs ?

**Comment by kenken64** [comment]
FAIL  test/client.test.ts (10.746s)
  ● Console

    console.log test/client.test.ts:36
      Account 1 address 54eefe5c5cd6ab32a70b43ed23d8ec7eb4f50697c973fe20d67c0b4022de6caf

  ● LibraClient › should get accountState correctly

    3 INVALID_ARGUMENT: The Address [165, 31, 66, 163, 78, 199, 102, 122, 118, 216, 138, 30, 237, 193, 37, 145, 206, 46, 201, 126, 221, 61, 246, 154, 238, 92, 77, 123, 247, 249, 143, 14] is of invalid length

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

  ● LibraClient › should query account state and transfer

    3 INVALID_ARGUMENT: The Address [84, 238, 254, 92, 92, 214, 171, 50, 167, 11, 67, 237, 35, 216, 236, 126, 180, 245, 6, 151, 201, 115, 254, 32, 214, 124, 11, 64, 34, 222, 108, 175] is of invalid length

      at Object.<anonymous>.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1209:28)
      at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:847:24)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       2 failed, 15 passed, 17 total
Snapshots:   0 total
Time:        13.871s, estimated 34s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kulap-libra@2.0.7 test: `jest`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kulap-libra@2.0.7 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
